### PR TITLE
Add license

### PR DESCRIPTION
**Pull request by mmagician**
Double license

### CODE REVIEW

**Review by Antonio95 — APPROVED** [review]
LGTM! Just to confirm: you want to keep HungryCatsStudio as the author name here instead of the new name, right?

**Comment by mmagician** [comment]
Oh. Nope, didn't realize that

**Comment by mmagician** [comment]
But actually we don't have our new page setup yet, let's leave as is

**Review by Cesar199999 — APPROVED** [review]
All good :)

**Pull request merged**
